module("arcade", package.seeall)
require "arcade/player"
require "arcade/misc"
require "arcade/alien"
require "arcade/asteroid"
require "arcade/laser"
require "arcade/main"
require "arcade/powerup"
require "arcade/galaxy"